# Generated by Django 2.0 on 2019-07-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190703_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmodel',
            name='todos',
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.OrganizationModel'),
        ),
    ]
