# Generated by Django 2.0 on 2019-07-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190703_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='active_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='todo.OrganizationModel'),
        ),
    ]
