# Generated by Django 2.0 on 2019-07-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_profilemodel_active_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='organizatons',
            new_name='organizations',
        ),
    ]
